In [1]:
import numpy as np

In [15]:
arreglo_np=np.array([1,2,3,4,5])

In [3]:
type(arreglo_np)

numpy.ndarray

In [14]:
tupla_np=np.array((1,2,3,4,5))

In [16]:
type(tupla_np)

numpy.ndarray

In [8]:
np.zeros((1))

array([0.])

In [9]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
np.empty((5,5))

array([[1.06045569e-311, 1.06045720e-311, 1.06045722e-311,
        1.06045727e-311, 1.06045727e-311],
       [1.06045728e-311, 1.06045728e-311, 1.06045729e-311,
        1.06045730e-311, 1.06045730e-311],
       [1.06045730e-311, 1.06045730e-311, 1.06045730e-311,
        1.06045730e-311, 1.06045730e-311],
       [1.06045730e-311, 1.06045730e-311, 1.06045730e-311,
        1.06045730e-311, 1.06045730e-311],
       [1.06045730e-311, 1.06045730e-311, 1.06045730e-311,
        1.06045730e-311, 1.06045730e-311]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
arreglo_pares=(np.arange(0,20,2))

In [30]:
arreglo_pares.size

10

In [33]:
arreglo_pares.shape

(10,)

In [34]:
arreglo_pares.reshape((5,2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [35]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [38]:
a=np.array([10,10,10])
b=np.array([5,5,5])

In [39]:
#Suma
a+b

array([15, 15, 15])

In [41]:
#Resta
a-b

array([5, 5, 5])

In [43]:
#Multiplicacion
a*b

array([50, 50, 50])

In [44]:
#Division
a/b

array([2., 2., 2.])

In [47]:
#Modulo
a % b

array([0, 0, 0], dtype=int32)

In [48]:
a*3

array([30, 30, 30])

In [49]:
arreglo_doce=np.arange(12)

In [50]:
arreglo_doce>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [53]:
arreglo_doce.all

<function ndarray.all>

In [55]:
A=np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [57]:
B=np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [58]:
A * B

array([[ 0,  5],
       [12, 21]])

In [59]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [60]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [62]:
arreglo_tres=np.arange(3)
arreglo_tres+=2
arreglo_tres

array([2, 3, 4])

In [63]:
arreglo_tres.sum()

9

In [65]:
arreglo_tres.min()

2

In [66]:
arreglo_tres.max()

4

In [68]:
arreglo_tres_cuatro=np.arange(24).reshape(6,2,2)
arreglo_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [69]:
arreglo_tres_cuatro.sum(axis=0)

array([[60, 66],
       [72, 78]])

In [70]:
arreglo_tres_cuatro.sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36],
       [42, 44]])

In [71]:
arreglo_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])