In [1]:
import numpy as np

In [4]:
angulos_cero_noventa=np.array([0,30,45,60,90])
angulos_cero_noventa

array([ 0, 30, 45, 60, 90])

In [6]:
angulos_radianes=angulos_cero_noventa*np.pi/180
angulos_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
np.sin(angulos_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [8]:
np.cos(angulos_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
arreglo_random_diez=np.random.rand(10)*10
arreglo_random_diez

array([7.25784244, 8.18198295, 2.61179643, 8.8157962 , 5.59920095,
       9.92987936, 6.78726375, 1.65899941, 2.51119479, 9.58315939])

In [16]:
numero_random=np.random.randint(10)
numero_random

5

In [17]:
#Parametros: Numero Inferior, Numero Superior, Dimension
enteros_random=np.random.randint(-10,10,10)
enteros_random

array([ -9,  -3,   5,   5,   3,   8, -10,   0,  -9,   4])

In [18]:
enteros_random.mean()

-0.6