# Reshaping

In [1]:
import numpy as np

In [2]:
paises_uno=['Ecuador','USA','México','Cuba','Venezuela']

In [3]:
paises_dos=['China','Japón','Taiwan','Brazil','Perú']

In [4]:
arreglo_paises_2d=np.array((paises_uno,paises_dos))

In [5]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'México', 'Cuba', 'Venezuela'],
       ['China', 'Japón', 'Taiwan', 'Brazil', 'Perú']], dtype='<U9')

In [6]:
arreglo_paises_2d.shape

(2, 5)

In [8]:
arreglo_paises_2d.flatten()

array(['Ecuador', 'USA', 'México', 'Cuba', 'Venezuela', 'China', 'Japón',
       'Taiwan', 'Brazil', 'Perú'], dtype='<U9')

In [9]:
arreglo_paises_2d.flatten().shape

(10,)

In [11]:
arreglo_paises_2d.flatten().reshape(1,5,2)

array([[['Ecuador', 'USA'],
        ['México', 'Cuba'],
        ['Venezuela', 'China'],
        ['Japón', 'Taiwan'],
        ['Brazil', 'Perú']]], dtype='<U9')

In [13]:
arreglo_paises_2d.flatten().reshape(5,-1)  #El -1 indica que se coloquen los elementos que se logren llenar

array([['Ecuador', 'USA'],
       ['México', 'Cuba'],
       ['Venezuela', 'China'],
       ['Japón', 'Taiwan'],
       ['Brazil', 'Perú']], dtype='<U9')

In [14]:
arreglo_paises_2d.T

array([['Ecuador', 'China'],
       ['USA', 'Japón'],
       ['México', 'Taiwan'],
       ['Cuba', 'Brazil'],
       ['Venezuela', 'Perú']], dtype='<U9')

In [15]:
arreglo_paises=arreglo_paises_2d.flatten()

In [16]:
arreglo_paises

array(['Ecuador', 'USA', 'México', 'Cuba', 'Venezuela', 'China', 'Japón',
       'Taiwan', 'Brazil', 'Perú'], dtype='<U9')

In [17]:
np.split(arreglo_paises,2)

[array(['Ecuador', 'USA', 'México', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['China', 'Japón', 'Taiwan', 'Brazil', 'Perú'], dtype='<U9')]

In [18]:
arreglo_doce=np.arange(12)

In [19]:
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.split(arreglo_doce,[1,3,5,9])

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11])]

In [21]:
arreglo_paises

array(['Ecuador', 'USA', 'México', 'Cuba', 'Venezuela', 'China', 'Japón',
       'Taiwan', 'Brazil', 'Perú'], dtype='<U9')

In [32]:
np.hsplit(arreglo_paises,5)

[array(['Ecuador', 'USA'], dtype='<U9'),
 array(['México', 'Cuba'], dtype='<U9'),
 array(['Venezuela', 'China'], dtype='<U9'),
 array(['Japón', 'Taiwan'], dtype='<U9'),
 array(['Brazil', 'Perú'], dtype='<U9')]

In [31]:
np.vsplit(arreglo_paises_2d,2)

[array([['Ecuador', 'USA', 'México', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['China', 'Japón', 'Taiwan', 'Brazil', 'Perú']], dtype='<U9')]

In [34]:
paises_1,paises_2,paises_3,paises_4,paises_5=np.hsplit(arreglo_paises,5)


array(['México', 'Cuba'], dtype='<U9')

In [35]:
paises_1

array(['Ecuador', 'USA'], dtype='<U9')

In [36]:
paises_2

array(['México', 'Cuba'], dtype='<U9')