# Indices

In [3]:
import numpy as np

In [3]:
numeros=np.arange(11)**2

In [4]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
indices=[1,3,5,7]

In [7]:
numeros[indices]

array([ 1,  9, 25, 49], dtype=int32)

In [8]:
arreglo_frutas = np.array([
    ['Piña','Pera','Sandía','Manzana'],
    ['Uva','Mora','Toronja','Naranja'],
    ['Plátano','Papaya','Mango','Fresa']
])

In [9]:
arreglo_frutas.shape

(3, 4)

In [10]:
arreglo_filas=np.array([
    [0,1],
    [2,1],
    [2,2]
])
arreglo_filas

array([[0, 1],
       [2, 1],
       [2, 2]])

In [11]:
arreglo_columnas=np.array([
    [1,3],
    [3,2],
    [0,2]
])
arreglo_columnas

array([[1, 3],
       [3, 2],
       [0, 2]])

In [12]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Pera', 'Naranja'],
       ['Fresa', 'Toronja'],
       ['Plátano', 'Mango']], dtype='<U7')

# Deber


In [9]:
arreglo_ciudades=np.array([[['Quito','Guayaquil'],['Machala','Manta']],[['Ambato','Cuenca'],['Latacunga','Portoviejo']]])
arreglo_ciudades

array([[['Quito', 'Guayaquil'],
        ['Machala', 'Manta']],

       [['Ambato', 'Cuenca'],
        ['Latacunga', 'Portoviejo']]], dtype='<U10')

In [10]:
arreglo_ciudades.shape

(2, 2, 2)

In [19]:
indices_1dim=np.array([
    [0,0],
    [0,1]
])
indices_1dim

array([[0, 0],
       [0, 1]])

In [20]:
indices_2dim=np.array([
    [1,0],
    [1,1]
])
indices_2dim

array([[1, 0],
       [1, 1]])

In [27]:
indices_3dim=np.array([
    [0,0],
    [1,1]
])
indices_3dim

array([[0, 0],
       [1, 1]])

In [28]:
arreglo_ciudades[indices_1dim,indices_2dim,indices_3dim]

array([['Machala', 'Quito'],
       ['Manta', 'Portoviejo']], dtype='<U10')