# EJERCICIOS CON NUMPY

In [1]:
import numpy as np

## Ejercicio 1: Problemas de Matrices
#### Bibliografía: https://www.superprof.es/apuntes/escolar/matematicas/algebralineal/matrices/matrices.html#tema_1
![image.png](https://www.superprof.es/apuntes/file/2019/05/50-15577554830097-764.gif)
## Calcular 
### A+B
### A-B
### AxB
### BxA
### A.B
### A^t

In [18]:
#A
A=np.array([[2,0,1],[3,0,0],[5,1,1]])
A

array([[2, 0, 1],
       [3, 0, 0],
       [5, 1, 1]])

In [5]:
#B
B=np.array([[1,0,1],[1,2,1],[1,1,0]])
B

array([[1, 0, 1],
       [1, 2, 1],
       [1, 1, 0]])

In [7]:
#A+B
A+B

array([[3, 0, 2],
       [4, 2, 1],
       [6, 2, 1]])

In [8]:
#A-B
A-B

array([[ 1,  0,  0],
       [ 2, -2, -1],
       [ 4,  0,  1]])

In [19]:
#AxB
A*B

array([[2, 0, 1],
       [3, 0, 0],
       [5, 1, 0]])

In [20]:
#BxA
B*A

array([[2, 0, 1],
       [3, 0, 0],
       [5, 1, 0]])

In [21]:
#A.B
np.dot(A,B)

array([[3, 1, 2],
       [3, 0, 3],
       [7, 3, 6]])

In [22]:
#A^t
np.transpose(A)

array([[2, 3, 5],
       [0, 0, 1],
       [1, 0, 1]])

## Calcular
#### Bibliografía: http://www.edu.xunta.gal/centros/iesvilalonga/system/files/operaciones%20matrices_0.pdf
### -2A+3B
### (1/2)A.B
### B.(-A)
### A.A - B.B

In [25]:
(-2*A)+(3*B)

array([[-1,  0,  1],
       [-3,  6,  3],
       [-7,  1, -2]])

In [27]:
((1.0/2.0)*A).dot(B)

array([[1.5, 0.5, 1. ],
       [1.5, 0. , 1.5],
       [3.5, 1.5, 3. ]])

In [28]:
B.dot(-1*A)

array([[ -7,  -1,  -2],
       [-13,  -1,  -2],
       [ -5,   0,  -1]])

In [29]:
A.dot(A)-B.dot(B)

array([[ 7,  0,  2],
       [ 2, -5,  0],
       [16, -1,  4]])

## Ejercicio 2: Problemas de Trigonometría
#### Bibliografía: https://www.matesfacil.com/ESO/geometria_plana/trigonometria/problemas-resueltos-trigonometria-secundaria-seno-coseno-triangulo-angulo.html
![image.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/T1.png)
![image.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/T2.png)
![image.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/T3.png)
### Problema 1:
#### Se desea sujetar un poste de 20 metros de altura con un cable que parte de la parte superior del mismo hasta el suelo de modo que forme un ángulo de 30º. Calcular el precio del cable si cada metro cuesta 12 dolares.
![image.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/P1.png)



In [35]:
def problema1():
    cat_opuesto=20
    angulo=30*np.pi/180
    precio_por_metro=12
    hipotenusa=cat_opuesto/np.sin(angulo)
    resultado_1=hipotenusa*precio_por_metro
    print(f"El precio total del cableado es de: {resultado}$")

problema1()

El precio total del cableado es de: 480.0000000000001$


### Problema 2:
#### Calcular la altura, a, de un árbol sabiendo que, si nos situamos 8 metros de la base del tronco, vemos la parte superior de su copa en un ángulo de 36.87º.

![image.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/P2.png)

In [37]:
def problema2():
    cat_adayacente=8
    angulo=(36.87)*np.pi/180
    resultado=np.tan(angulo)*cat_adayacente
    print(f"La altua del arbol es de {resultado}mts")
    
problema2()

La altua del arbol es de 6.000022330242729mts


### Problema 3:
#### Calcular cuánto mide la mediana de un triángulo equilátero (los tres ángulos son de 60 grados) cuyos lados miden 12cm.
![img.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/P3b.png)


In [39]:
def problema3():
    angulo=60*np.pi/180
    hipotenusa=12
    m=hipotenusa*np.sin(angulo)
    print(f"La altura de la mediana es de {m}mts")
    
problema3()

La altura de la mediana es de 10.392304845413264mts


### Problema 4:
#### Miguel desea calcular la altura de dos edificios que están situados a 100 metros el uno del otro. Como tiene acceso al edificio más alto, observa que desde la azotea de dicho edificio se avista la azotea del otro bajo un ángulo de α=73,3∘. Desde la base del mismo edificio, se ve la azotea del otro edificio bajo un ángulo de β=19,29∘.¿Puede Miguel calcular la altura de los edificios con los tres datos con los que cuenta? En caso afirmativo, ¿cuál es la altura de cada uno?
![imagen.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/P9.png)

![img.png](https://www.matesfacil.com/ESO/geometria_plana/trigonometria/P9b.png)

In [42]:
def problema4():
    angulo_a=73.3*np.pi/180
    angulo_b=19.29*np.pi/180
    c=100
    d=c
    x=d/np.tan(angulo_a)
    y=np.tan(angulo_b)*c
    altura_edif_a=x+y
    altura_edif_b=y
    print(f"La altura del edificio A es: {altura_edif_a}mts.\nLa altura del edificio B es:{altura_edif_b}mts.")
    
problema4()

La altura del edificio A es: 65.00134723218488mts.
La altura del edificio B es:34.999909450529955mts.


## Ejercicio 4:
Descripción ejercicio

## Ejercicio 5:
Descripción ejercicio

## Ejercicio 6:
Descripción ejercicio

## Ejercicio 7:
Descripción ejercicio

## Ejercicio 8:
 Descripción ejercicio

## Ejercicio 9:
Descripción ejercicio

## Ejercicio 10:
Descripción ejercicio

## Ejercicio 11:
Descripción ejercicio

## Ejercicio 12:
Descripción ejercicio

## Ejercicio 13:
Descripción ejercicio

## Ejercicio 14:
Descripción ejercicio

## Ejercicio 15:
Descripción ejercicio

## Ejercicio 16:
Descripción ejercicio

## Ejercicio 17:
Descripción ejercicio

## Ejercicio 18:
Descripción ejercicio